### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by wjn0** [Lezcano/geotorch#13]
Thanks for a great package!

I'm having trouble setting the initial value of a constrained variable. Minimum reproducible example (from the README):

```python
>>> import torch
>>> from torch import nn
>>> import geotorch
>>>
>>> torch.__version__
'1.8.0'
>>> geotorch.__version__
'0.1.0'
>>>
>>> linear = nn.Linear(64, 64)
>>> geotorch.orthogonal(linear, "weight")
>>> linear.weight = torch.eye(64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$HOME/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 995, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
```

In case it matters, I am using Python 3.9.2.

**Comment by Lezcano** [comment]
Have you installed the package from github, as it says in the README? The package on pip is not updated (entirely my fault, I should really get that going at some point).
Install `geotorch` by doing:
```bash
pip install git+https://github.com/Lezcano/geotorch/
```
or by cloning the repo and installing it manually.

**Comment by wjn0** [comment]
Ah, that fixed it - sorry for missing that. Thanks very much for the prompt response!
