### ISSUE TITLE
Error on initialization Tensor not contained in PSSD

### ISSUE THREAD

**Issue by EdwardRaff** [Lezcano/geotorch#15]
Randomly, I get the below error at initialization. It happens with PyTorch 1.8.1, and using the example code from the docs

```python
self.M = nn.Parameter(torch.rand(size=(256, 256)))
geotorch.positive_semidefinite(self, "M")
```

is enough to cause a problem within a Module definition. I've not yet had the error happen after initialization and during training. 

```
Tensor not contained in PSSD(
  n=256
  (0): Stiefel(n=256, k=256, triv=matrix_exp)
  (1): Rn(n=256)
). Got
(tensor([ 3.8247e+00,  3.7747e+00,  3.6989e+00,  3.6000e+00,  3.5833e+00,
         3.5031e+00,  3.4670e+00,  3.4062e+00,  3.4000e+00,  3.3106e+00,
         3.2411e+00,  3.1645e+00,  3.0778e+00,  3.0292e+00,  2.9826e+00,
         2.9379e+00,  2.8955e+00,  2.8642e+00,  2.8168e+00,  2.8006e+00,
         2.7573e+00,  2.7106e+00,  2.6791e+00,  2.6573e+00,  2.6322e+00,
         2.5699e+00,  2.5364e+00,  2.5296e+00,  2.4885e+00,  2.4640e+00,
         2.4263e+00,  2.4049e+00,  2.3801e+00,  2.3288e+00,  2.3193e+00,
         2.2720e+00,  2.2427e+00,  2.2351e+00,  2.2044e+00,  2.1853e+00,
         2.1702e+00,  2.1395e+00,  2.1172e+00,  2.0862e+00,  2.0769e+00,
         2.0350e+00,  2.0008e+00,  1.9624e+00,  1.9416e+00,  1.9255e+00,
         1.8966e+00,  1.8455e+00,  1.8381e+00,  1.8143e+00,  1.8043e+00,
         1.7621e+00,  1.7544e+00,  1.7423e+00,  1.7031e+00,  1.6941e+00,
         1.6761e+00,  1.6508e+00,  1.6293e+00,  1.6204e+00,  1.5964e+00,
         1.5703e+00,  1.5632e+00,  1.5491e+00,  1.5058e+00,  1.4713e+00,
         1.4555e+00,  1.4520e+00,  1.4251e+00,  1.4026e+00,  1.3831e+00,
         1.3698e+00,  1.3429e+00,  1.3210e+00,  1.3175e+00,  1.2850e+00,
         1.2790e+00,  1.2654e+00,  1.2511e+00,  1.2399e+00,  1.2246e+00,
         1.1950e+00,  1.1777e+00,  1.1633e+00,  1.1499e+00,  1.1298e+00,
         1.1138e+00,  1.1045e+00,  1.0955e+00,  1.0744e+00,  1.0565e+00,
         1.0474e+00,  1.0334e+00,  1.0240e+00,  1.0008e+00,  9.9861e-01,
         9.9170e-01,  9.6764e-01,  9.5716e-01,  9.4440e-01,  9.2202e-01,
         9.1461e-01,  9.0652e-01,  8.9787e-01,  8.8027e-01,  8.7056e-01,
         8.6487e-01,  8.3175e-01,  8.1901e-01,  8.1444e-01,  8.0160e-01,
         7.9311e-01,  7.8946e-01,  7.6787e-01,  7.5898e-01,  7.4889e-01,
         7.4063e-01,  7.2527e-01,  7.2042e-01,  6.9469e-01,  6.8660e-01,
         6.7460e-01,  6.6354e-01,  6.5471e-01,  6.4855e-01,  6.3990e-01,
         6.3743e-01,  6.3105e-01,  6.2178e-01,  6.1211e-01,  6.0192e-01,
         5.9400e-01,  5.7176e-01,  5.6133e-01,  5.4624e-01,  5.2755e-01,
         5.2498e-01,  5.1198e-01,  5.0673e-01,  5.0041e-01,  4.9502e-01,
         4.8107e-01,  4.7528e-01,  4.6593e-01,  4.6015e-01,  4.4301e-01,
         4.3815e-01,  4.3327e-01,  4.2120e-01,  4.0957e-01,  3.9892e-01,
         3.9058e-01,  3.8309e-01,  3.8147e-01,  3.7352e-01,  3.6457e-01,
         3.5520e-01,  3.5129e-01,  3.3950e-01,  3.3678e-01,  3.2362e-01,
         3.1534e-01,  3.1092e-01,  3.0481e-01,  2.9021e-01,  2.8767e-01,
         2.8236e-01,  2.7318e-01,  2.6519e-01,  2.6043e-01,  2.5385e-01,
         2.4521e-01,  2.3967e-01,  2.3143e-01,  2.2369e-01,  2.2308e-01,
         2.1247e-01,  2.0372e-01,  2.0049e-01,  1.9481e-01,  1.9068e-01,
         1.8485e-01,  1.8031e-01,  1.7281e-01,  1.7046e-01,  1.6684e-01,
         1.6048e-01,  1.5335e-01,  1.5150e-01,  1.4633e-01,  1.3898e-01,
         1.3572e-01,  1.3068e-01,  1.2853e-01,  1.2517e-01,  1.1826e-01,
         1.1534e-01,  1.1302e-01,  1.0915e-01,  1.0521e-01,  9.6949e-02,
         9.3288e-02,  8.9677e-02,  8.3769e-02,  8.2001e-02,  7.8403e-02,
         7.5017e-02,  7.3773e-02,  6.7579e-02,  6.3032e-02,  6.0493e-02,
         5.7282e-02,  5.4498e-02,  5.1430e-02,  5.0613e-02,  4.7330e-02,
         4.4593e-02,  4.0078e-02,  3.9779e-02,  3.7704e-02,  3.5867e-02,
         3.3504e-02,  3.0591e-02,  2.8566e-02,  2.7471e-02,  2.5519e-02,
         2.3299e-02,  2.1866e-02,  2.1535e-02,  1.9136e-02,  1.6720e-02,
         1.5590e-02,  1.3703e-02,  1.2581e-02,  1.1524e-02,  9.6512e-03,
         8.5254e-03,  8.0568e-03,  6.5441e-03,  5.7102e-03,  4.6747e-03,
         4.3863e-03,  3.5337e-03,  3.0264e-03,  1.3910e-03,  1.2277e-03,
         7.2367e-04,  5.6175e-04,  2.4230e-04,  1.8732e-04,  5.9763e-05,
        -1.0149e-06]), tensor([[-0.0169,  0.0209,  0.0364,  ..., -0.0517, -0.0923, -0.0353],
        [-0.1337, -0.0161, -0.0759,  ...,  0.0348, -0.0387,  0.0934],
        [ 0.0157,  0.0989,  0.0694,  ..., -0.0339,  0.0814, -0.0115],
        ...,
        [-0.0137, -0.0050, -0.0050,  ..., -0.0251, -0.0578, -0.0589],
        [-0.0382, -0.0102,  0.1440,  ..., -0.0455, -0.0192,  0.0240],
        [ 0.0857,  0.0659,  0.0028,  ...,  0.0028, -0.0217, -0.0888]]))

```

**Comment by Lezcano** [comment]
Uh, that's caused by numerical errors in the sampling that's done internally in `geotorch.positive_semidefinite` and some checks that I was doing when initializing . I will push a PR that solves that, so if you re-install master that should never happen again.

Just for it not to bite you, as it says in the documentation, when you register a constraint with any of the methods. As such, you can start your parameters with `torch.empty` rather than `torch.rand`.
For example, with `geotorch.positive_semidefinite`, it samples a new symmetric positive semidefinite matrix according to this function:
https://github.com/Lezcano/geotorch/blob/6cf490caee79c6424e3c13c440d9738a0dcc6cf0/geotorch/symmetric.py#L232-L250

I realised that that method does not appear in the documentation of the PSSD manifold. This PR will also fix that.

**Comment by Lezcano** [comment]
If everything's gone well, the documentation for the sampling method used for symmetric positive semidefinite matrices should appear here any time soon (when the docs are recompiled):
https://geotorch.readthedocs.io/en/latest/psd/pssd.html

**Comment by EdwardRaff** [comment]
Thanks for the super fast fix/reply! 

I think this is touching on something I found kinda confusing / not well explained in the docs. From the example on the main page I thought I needed to initialize it myself. Lets say W is the underlying unconstrained problem and M is the constrained result M = F(W) 

So I was doing init W, register F. Is that not correct? Then those docs have:

```python
layer = nn.Linear(20, 20)
M = PSSD(layer.weight.size())
geotorch.register_parametrization(layer, "weight", M)
layer.weight = M.sample()
```

which to me looks like W is created, then we sample some M, and set W = M? I'm very confused on the mechanics of this example. 

I was also confused by the other part of the Github example that has 

```python
# You may initialize the parametrized weights by assigning to them
self.linear.weight = torch.eye(128, 64)
```

Is this: 
1.  setting W = I , and now the value M = F(W) has automatically changed
2. setting M = I, and now the unconstrained W has somehow been altered W =  f^{-1}(M)? [and if this is the case, what happens if we set it to something that is outside the constraints that are selected?]

**Comment by Lezcano** [comment]
Uh, this is very good feedback thank you!

So, what's going on is that `M`  is a module that implements a function `f` that maps R^{n x n} into PSSD(n). In the third line with that `register_parametrization`, what happens is that you say "from now on, whenever I call `layer.weight`, I want to get `f(layer.weight)` instead (i.e. a PSSD(n) matrix).
In the fourth line you are sampling a PSSD(n) matrix and assigning it to `layer.weight` to initialize the constraints. As such you could write
```python
X = M.sample()
layer.weight = X
assert torch.allclose(layer.weight, X)
```
but `layer.weight` would still be constrained. To see this do
```python
print(layer)
```
In particular, the unconstrained weight is under `layer.parametrizations.weight`.

In the example in the readme, it's the same thing but initializing it to be the identity matrix. As such, oyur second guess is exactly correct. If we set it to something outside the constraints, you get the exception that took you to open this issue :D

I agree that this could be explained a bit better. I am waiting to have the tutorial on all this things accepted into pytorch/tutorials, but you can read it here, and it may help to wrap your head around all these things:
https://deploy-preview-1444--pytorch-tutorials-preview.netlify.app/intermediate/parametrizations.html
Also, if you are a native speaker and you happen to find grammatical errors, please open a review in the PR for me to correct them!
https://github.com/pytorch/tutorials/pull/1444

Thank you in advance!

**Comment by EdwardRaff** [comment]
So I think this makes more sense now. I guess the last / remaining question would be, what is the prefered way to initialize a random not-yet-trained constrained layer? Should I:

1. Initialize something like a Linear layer for ReLU weights, and then register a parameterization?
2. Call the `.sample()` method and then assign that to the value (assuming everything has this inverse process implemented)? 


>Also, if you are a native speaker and you happen to find grammatical errors, please open a review in the PR for me to correct them!

I am a native speaker, but very dyslexic - I may not be so helpful. The tutorial definitely helps though, looking forward to this being first-class PyTorch functionality!

**Comment by Lezcano** [comment]
The preferred way is to just call `geotorch.positive_semidefinite(self, "weight")` and not to anything else. That will already initialize it to a sane value. Of course, if you know of a better initialisation for your own problem, you may use it simply assigning to `module.weight` after putting the constraint. It's basically the same drill as with a regular `nn.Linear` layer, which comes with its own initialization, but you can initialize it yourself if you prefer.
