### ISSUE TITLE
torch.qr is deprecated for torch==1.8.0

### ISSUE THREAD

**Issue by mortonjt** [Lezcano/geotorch#19]
As per the recent torch=1.8 release, `torch.qr` is now deprecated to `torch.linalg.qr`

https://pytorch.org/docs/stable/generated/torch.qr.html#torch.qr

**Comment by Lezcano** [comment]
Thanks for the note!

I updated `master` to be ready to support 1.8, but also the upcoming 1.9 release.

Feel free to reopen if you find any problems.
