### ISSUE TITLE
[feature request] "Multidimensional Shape Constraints"

### ISSUE THREAD

**Issue by teichert** [Lezcano/geotorch#20]
I just stumbled upon this project, and I'm amazed at the simple interface you have come up with! It would be awesome to have the same type of interface for the "shape constraints" of [Gupta et al. (2020)](http://www.mayagupta.org/publications/Multidimensional_Shape_Constraints_ICML_2020.pdf).  For example, let's say that I want to constrain the output of the final layer of a neural net to be monotonic or unimodal with respect to a particular slice of the input features to the net.  Would that be within scope for this project?

(I don't have time to work on a PR now, but I thought I'd at least check if this is even relevant to you all.)  Gupta et al. have a tensor-flow implementation: https://github.com/tensorflow/lattice

Either way, thanks for the interesting work!

**Comment by Lezcano** [comment]
What is called in the literature "geometric deep learning" mostly works with the ideas that your mention: putting constraints in the inner states of the neural network to help the training. Note that these work on the data, and their outputs are data-dependant.

GeoTorch just works (for now) on the parameters of the model, that is, it's not data-dependant. As such, I'm afraid that it'd not be possible to implement these shape constraints on GeoTorch.

Now, if you come up with a way to do so, we can discuss it here but, a priori, seems like quite a challenging thing to do.

**Comment by teichert** [comment]
Okay; thanks for considering.  I'll close for now.
