### ISSUE TITLE
"Close to" constraint?

### ISSUE THREAD

**Issue by sergeyf** [Lezcano/geotorch#24]
Hello,

I'd like to implement a nuclear norm minimization approach for matrix completion using your package. This requires a constraint that `|X_{ij} - S_{ij}| < eps` where `X` is the incomplete matrix and `S` is the optimization variable matrix. Is this possible?

Thanks!

**Comment by Lezcano** [comment]
Fwiw, I ended up testing the code above, so it should be fairly ready to be used :)
