### ISSUE TITLE
geotorch.optim

### ISSUE THREAD

**Issue by liumiao-p** [Lezcano/geotorch#26]
Don't geotorch need to implement a geometry optimizer? 
Why Euclidean torch.optim is stilled used to optimize geometry parameters(such as orthogonal parameters)?

**Comment by Lezcano** [comment]
The following papers of mine:
https://arxiv.org/abs/1901.08428
https://arxiv.org/abs/1909.09501
answer this question.

**Comment by liumiao-p** [comment]
Thanks, I'll take a look.

**Comment by liumiao-p** [comment]
I set args.constraints = 'orthogonal' and ExpRNNCell.recurrent_kernel.weight is orthogonal by geotorch.orthogonal( ).
I tried to check orthogonality during optimization by whether the multiply of recurrent_kernel.weight and its transpose equal to identity matrix, and the answer was no. So how can I check the  orthogonality during optimization?

**Comment by Lezcano** [comment]
I assume you are referring to the model in `sequential_mnist.py`.
could you post how are you running the model?
In that model, in the training loop, if you do `W = model.rnn.recurrent_kernel`, then `torch.dist(W.T @ W, torch.eye(W.shape[-1], device=W.device)` should be close to zero. Is that not the case?

**Comment by liumiao-p** [comment]
Below is how I change the model.
```
class Model(nn.Module):
    def __init__(self, hidden_size, permute):
        super(Model, self).__init__()
        self.permute = permute
        if self.permute:
            self.register_buffer("permutation", torch.randperm(784))
        self.rnn = ExpRNNCell(1, hidden_size)
        self.lin = nn.Linear(hidden_size, n_classes)
        self.loss_func = nn.CrossEntropyLoss()

    def forward(self, inputs):
        #check orthogonality
        orthogonal_ = self.rnn.recurrent_kernel.weight
        orthogonal_T = orthogonal_.t()
        res = torch.mm(orthogonal_,orthogonal_T)
        print(res) # far away from zero

        if self.permute:
            inputs = inputs[:, self.permutation]
        out_rnn = self.rnn.default_hidden(inputs[:, 0, ...])
        with geotorch.parametrize.cached():
            for input in torch.unbind(inputs, dim=1):
                out_rnn = self.rnn(input.unsqueeze(dim=1), out_rnn)
        return self.lin(out_rnn)

```

**Comment by Lezcano** [comment]
`res` shoudl be close to the identity matrix, so it'll surely be far enough from zero. See the code I posted above for how to do the check properly.

**Comment by liumiao-p** [comment]
sorry, I made a writing mistake. `res` is far from identity matrix.

**Comment by liumiao-p** [comment]
I'm terribly sorry . I didn't notice the negative exponent. `res`  is close to identity matrix. And can the non-diagonal element be exactly zero rather than close to?
`Train Epoch: 0 [128/60000 (0%)] Loss: 20.576336 Accuracy: 7.81% Best: 0.00%
tensor([[ 1.0000e+00, -1.2219e-08, -7.4806e-11,  ..., -6.1846e-11,
         -6.9122e-11, -6.9122e-11],
        [-1.2219e-08,  1.0000e+00,  2.5216e-10,  ..., -1.1642e-10,
         -1.1642e-10,  2.3283e-10],
        [-7.4806e-11,  2.5216e-10,  1.0000e+00,  ..., -2.3283e-10,
          1.1642e-10, -2.3283e-10],
        ...,
        [-6.1846e-11, -1.1642e-10, -2.3283e-10,  ...,  1.0000e+00,
         -6.5484e-11, -1.3097e-10],
        [-9.8225e-11,  5.8208e-10,  2.3283e-10,  ...,  0.0000e+00,
          1.0000e+00,  3.1805e-09],
        [-9.4587e-11,  1.1642e-10, -1.7462e-10,  ..., -2.9104e-11,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [256/60000 (0%)] Loss: 16.238478 Accuracy: 17.19%        Best: 0.00%
tensor([[ 1.0000e+00,  5.6905e-08, -7.0941e-11,  ...,  1.7462e-10,
         -4.7930e-10,  1.0550e-10],
        [ 5.6905e-08,  1.0000e+00, -4.3656e-11,  ...,  3.4925e-10,
          0.0000e+00, -1.1642e-10],
        [-7.0941e-11, -4.3656e-11,  1.0000e+00,  ...,  3.4925e-10,
          1.2506e-11,  7.2760e-12],
        ...,
        [ 1.7462e-10,  3.4925e-10,  3.4925e-10,  ...,  1.0000e+00,
         -2.9104e-11, -1.4552e-11],
        [-1.8190e-11, -6.9849e-10,  2.0236e-11,  ..., -9.0949e-12,
          1.0000e+00,  1.1099e-08],
        [ 6.9122e-11, -2.3283e-10,  0.0000e+00,  ..., -1.4552e-10,
          7.4506e-09,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [384/60000 (0%)] Loss: 14.642992 Accuracy: 18.75%        Best: 0.00%
tensor([[ 1.0000e+00, -1.7521e-08, -7.0031e-11,  ...,  5.8208e-10,
          1.2005e-10,  1.7462e-10],
        [-1.7521e-08,  1.0000e+00,  3.6380e-11,  ...,  1.4552e-10,
          0.0000e+00, -4.6566e-10],
        [-7.0031e-11,  3.6380e-11,  1.0000e+00,  ...,  2.3283e-10,
         -2.1828e-11, -1.7462e-10],
        ...,
        [ 5.8208e-10,  1.4552e-10,  2.3283e-10,  ...,  1.0000e+00,
          1.4552e-11,  1.1460e-10],
        [ 8.3674e-11, -4.6566e-10, -7.2760e-12,  ...,  3.5016e-11,
          1.0000e+00, -6.0427e-09],
        [ 1.4552e-10, -6.9849e-10, -1.1642e-10,  ...,  8.7311e-11,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [512/60000 (1%)] Loss: 7.779714  Accuracy: 35.94%        Best: 0.00%
tensor([[ 1.0000e+00, -2.9722e-09,  8.1855e-11,  ...,  0.0000e+00,
         -1.4552e-10,  2.6921e-10],
        [-2.9722e-09,  1.0000e+00,  6.9122e-11,  ...,  2.0373e-10,
          1.1642e-10,  2.3283e-10],
        [ 8.1855e-11,  6.9122e-11,  1.0000e+00,  ...,  0.0000e+00,
         -5.8208e-11,  1.1642e-10],
        ...,
        [ 0.0000e+00,  2.0373e-10,  0.0000e+00,  ...,  1.0000e+00,
         -3.6380e-12, -8.0036e-11],
        [ 2.9104e-11, -4.6566e-10, -2.3283e-10,  ...,  2.7285e-12,
          1.0000e+00,  6.1300e-10],
        [ 2.5830e-10, -4.6566e-10,  5.8208e-11,  ..., -5.9117e-11,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [640/60000 (1%)] Loss: 6.097362  Accuracy: 37.50%        Best: 0.00%
tensor([[ 1.0000e+00,  4.6931e-08, -2.4556e-11,  ..., -1.1642e-10,
         -2.3283e-10, -1.6735e-10],
        [ 4.6931e-08,  1.0000e+00, -1.5098e-10,  ...,  2.9104e-10,
         -1.1642e-10,  2.3283e-10],
        [-2.4556e-11, -1.5098e-10,  1.0000e+00,  ..., -2.3283e-10,
         -4.3656e-11,  1.1642e-10],
        ...,
        [-1.1642e-10,  2.9104e-10, -2.3283e-10,  ...,  1.0000e+00,
         -4.5475e-11, -2.5466e-11],
        [-5.8208e-11,  2.3283e-10, -2.9104e-11,  ..., -1.5007e-11,
          1.0000e+00, -5.4624e-09],
        [-7.2760e-11, -4.6566e-10,  1.1642e-10,  ...,  5.0932e-11,
         -7.4506e-09,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [768/60000 (1%)] Loss: 5.301270  Accuracy: 53.12%        Best: 0.00%
tensor([[ 1.0000e+00, -4.4449e-08, -1.5643e-10,  ...,  2.9104e-10,
          5.8208e-10,  1.4552e-11],
        [-4.4449e-08,  1.0000e+00, -1.0732e-10,  ..., -2.9104e-11,
          4.6566e-10,  1.1642e-10],
        [-1.5643e-10, -1.0732e-10,  1.0000e+00,  ..., -2.3283e-10,
          2.9104e-11, -1.1642e-10],
        ...,
        [ 2.9104e-10, -2.9104e-11, -2.3283e-10,  ...,  1.0000e+00,
         -5.7980e-11, -1.4370e-10],
        [ 3.2014e-10,  2.3283e-10,  1.0186e-10,  ..., -6.4119e-11,
          1.0000e+00,  1.2147e-08],
        [ 7.2760e-11,  0.0000e+00, -2.3283e-10,  ..., -1.3097e-10,
          1.4901e-08,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [896/60000 (1%)] Loss: 4.414509  Accuracy: 55.47%        Best: 0.00%
tensor([[ 1.0000e+00, -3.1222e-08,  3.6380e-11,  ..., -1.1642e-10,
          2.3283e-10,  1.2005e-10],
        [-3.1222e-08,  1.0000e+00,  3.7016e-10,  ...,  3.4925e-10,
         -2.3283e-10,  1.1642e-10],
        [ 3.6380e-11,  3.7016e-10,  1.0000e+00,  ...,  6.9849e-10,
         -1.4552e-11, -2.3283e-10],
        ...,
        [-1.1642e-10,  3.4925e-10,  6.9849e-10,  ...,  1.0000e+00,
          1.5007e-11,  1.6371e-10],
        [ 0.0000e+00, -2.3283e-10,  0.0000e+00,  ...,  8.6402e-12,
          1.0000e+00,  5.1950e-09],
        [ 1.4188e-10,  0.0000e+00,  1.1642e-10,  ...,  1.0186e-10,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [1024/60000 (1%)]        Loss: 2.768662  Accuracy: 63.28%        Best: 0.00%
tensor([[ 1.0000e+00,  2.8785e-08, -1.2551e-10,  ..., -2.9104e-10,
         -3.4925e-10, -2.8012e-10],
        [ 2.8785e-08,  1.0000e+00, -1.4370e-10,  ...,  0.0000e+00,
          0.0000e+00, -2.3283e-10],
        [-1.2551e-10, -1.4370e-10,  1.0000e+00,  ..., -2.3283e-10,
          2.9104e-11, -1.1642e-10],
        ...,
        [-2.9104e-10,  0.0000e+00, -2.3283e-10,  ...,  1.0000e+00,
          1.6144e-11, -1.8190e-12],
        [-2.3283e-10,  9.3132e-10,  4.3656e-11,  ...,  1.9782e-11,
          1.0000e+00, -3.4452e-09],
        [-1.7462e-10, -2.3283e-10,  1.1642e-10,  ..., -1.4552e-11,
          7.4506e-09,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [1152/60000 (2%)]        Loss: 2.417797  Accuracy: 61.72%        Best: 0.00%
tensor([[ 1.0000e+00, -6.8445e-08,  3.1287e-10,  ..., -1.7462e-10,
          2.9104e-10,  4.3656e-11],
        [-6.8445e-08,  1.0000e+00,  1.3642e-10,  ..., -5.8208e-11,
         -4.6566e-10,  5.8208e-10],
        [ 3.1287e-10,  1.3642e-10,  1.0000e+00,  ..., -6.9849e-10,
          0.0000e+00,  0.0000e+00],
        ...,
        [-1.7462e-10, -5.8208e-11, -6.9849e-10,  ...,  1.0000e+00,
         -4.7748e-11,  4.7294e-11],
        [ 4.0745e-10, -1.3970e-09, -2.1828e-11,  ..., -3.5016e-11,
          1.0000e+00, -7.8771e-09],
        [ 1.4552e-10,  6.9849e-10, -1.1642e-10,  ..., -3.6380e-11,
         -1.4901e-08,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [1280/60000 (2%)]        Loss: 2.603057  Accuracy: 53.91%        Best: 0.00%
tensor([[ 1.0000e+00, -7.3889e-08, -1.6371e-10,  ...,  1.1642e-10,
          2.3283e-10,  5.8208e-11],
        [-7.3889e-08,  1.0000e+00,  7.2760e-12,  ..., -1.7462e-10,
          6.9849e-10,  4.6566e-10],
        [-1.6371e-10,  7.2760e-12,  1.0000e+00,  ...,  0.0000e+00,
          1.4552e-11,  2.3283e-10],
        ...,
        [ 1.1642e-10, -1.7462e-10,  0.0000e+00,  ...,  1.0000e+00,
         -3.3651e-11,  4.3656e-11],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.5916e-11,
          1.0000e+00, -4.7748e-09],
        [-5.0932e-11,  3.4925e-10,  1.1642e-10,  ...,  4.3656e-11,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [1408/60000 (2%)]        Loss: 1.617504  Accuracy: 67.97%        Best: 0.00%
tensor([[ 1.0000e+00,  6.2937e-10, -9.6406e-11,  ...,  0.0000e+00,
         -1.1642e-10,  8.7311e-11],
        [ 6.2937e-10,  1.0000e+00,  4.8203e-11,  ...,  3.4925e-10,
          4.6566e-10,  0.0000e+00],
        [-9.6406e-11,  4.8203e-11,  1.0000e+00,  ..., -2.3283e-10,
         -1.4552e-11,  1.1642e-10],
        ...,
        [ 0.0000e+00,  3.4925e-10, -2.3283e-10,  ...,  1.0000e+00,
          5.5479e-11,  7.6398e-11],
        [-5.8208e-11, -1.1642e-09, -5.8208e-11,  ...,  6.3665e-12,
          1.0000e+00, -3.1769e-09],
        [-7.2760e-11,  0.0000e+00,  2.3283e-10,  ...,  9.4587e-11,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [1536/60000 (2%)]        Loss: 1.434912  Accuracy: 67.97%        Best: 0.00%
tensor([[ 1.0000e+00,  8.3373e-09,  4.4565e-10,  ..., -1.7462e-10,
          5.8208e-11, -7.2760e-11],
        [ 8.3373e-09,  1.0000e+00,  2.8194e-10,  ..., -1.1642e-10,
          2.3283e-10, -3.4925e-10],
        [ 4.4565e-10,  2.8194e-10,  1.0000e+00,  ...,  0.0000e+00,
         -5.8208e-11,  0.0000e+00],
        ...,
        [-1.7462e-10, -1.1642e-10,  0.0000e+00,  ...,  1.0000e+00,
         -8.3674e-11,  4.3656e-11],
        [ 0.0000e+00, -2.3283e-10, -8.7311e-11,  ..., -7.0031e-11,
          1.0000e+00,  2.2046e-09],
        [-8.7311e-11, -3.4925e-10,  1.1642e-10,  ...,  3.6380e-11,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [1664/60000 (3%)]        Loss: 2.003700  Accuracy: 62.50%        Best: 0.00%
tensor([[ 1.0000e+00, -3.3622e-08,  1.8190e-10,  ..., -1.7462e-10,
          1.7462e-10,  5.8208e-11],
        [-3.3622e-08,  1.0000e+00,  2.8740e-10,  ..., -1.7462e-10,
          2.3283e-10, -4.6566e-10],
        [ 1.8190e-10,  2.8740e-10,  1.0000e+00,  ...,  6.9849e-10,
          5.8208e-11,  0.0000e+00],
        ...,
        [-1.7462e-10, -1.7462e-10,  6.9849e-10,  ...,  1.0000e+00,
         -4.5475e-12,  5.0932e-11],
        [-2.9104e-11, -4.6566e-10,  9.4587e-11,  ..., -2.9104e-11,
          1.0000e+00, -1.6722e-08],
        [-2.9104e-11, -4.6566e-10, -1.1642e-10,  ...,  4.3656e-11,
         -1.4901e-08,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [1792/60000 (3%)]        Loss: 2.131362  Accuracy: 60.16%        Best: 0.00%
tensor([[ 1.0000e+00, -4.4763e-08, -3.4561e-11,  ...,  5.8208e-11,
         -1.1642e-10,  1.4552e-11],
        [-4.4763e-08,  1.0000e+00,  2.0282e-10,  ..., -5.8208e-11,
          4.6566e-10, -1.1642e-10],
        [-3.4561e-11,  2.0282e-10,  1.0000e+00,  ...,  9.3132e-10,
          3.6380e-11,  0.0000e+00],
        ...,
        [ 5.8208e-11, -5.8208e-11,  9.3132e-10,  ...,  1.0000e+00,
          1.4552e-11,  1.1096e-10],
        [ 2.9104e-11,  6.9849e-10,  1.6371e-11,  ...,  6.0027e-11,
          1.0000e+00,  1.1278e-09],
        [ 1.4552e-11,  0.0000e+00, -2.3283e-10,  ...,  1.4552e-10,
          7.4506e-09,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [1920/60000 (3%)]        Loss: 1.699547  Accuracy: 63.28%        Best: 0.00%
tensor([[ 1.0000e+00, -4.1789e-08,  2.4374e-10,  ...,  1.1642e-10,
         -2.9104e-10,  2.7649e-10],
        [-4.1789e-08,  1.0000e+00,  9.2768e-11,  ...,  0.0000e+00,
          2.3283e-10, -2.3283e-10],
        [ 2.4374e-10,  9.2768e-11,  1.0000e+00,  ...,  0.0000e+00,
          1.4552e-11,  3.4925e-10],
        ...,
        [ 1.1642e-10,  0.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
          3.6380e-11,  3.6380e-12],
        [-1.1642e-10,  9.3132e-10,  9.4587e-11,  ..., -4.8203e-11,
          1.0000e+00, -3.4761e-09],
        [ 2.4738e-10, -3.4925e-10,  3.4925e-10,  ..., -5.0932e-11,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [2048/60000 (3%)]        Loss: 1.162014  Accuracy: 77.34%        Best: 0.00%
tensor([[ 1.0000e+00, -2.9431e-09,  2.3647e-10,  ...,  2.3283e-10,
         -2.9104e-10,  1.1642e-10],
        [-2.9431e-09,  1.0000e+00,  9.8225e-11,  ..., -2.9104e-10,
          2.3283e-10,  3.4925e-10],
        [ 2.3647e-10,  9.8225e-11,  1.0000e+00,  ..., -1.8626e-09,
          1.4552e-11, -2.3283e-10],
        ...,
        [ 2.3283e-10, -2.9104e-10, -1.8626e-09,  ...,  1.0000e+00,
          1.4188e-10,  6.1846e-11],
        [-2.3283e-10, -1.1642e-09,  5.0932e-11,  ...,  8.0036e-11,
          1.0000e+00,  7.8708e-09],
        [-2.9104e-11,  1.1642e-10,  0.0000e+00,  ...,  2.1828e-11,
          7.4506e-09,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [2176/60000 (3%)]        Loss: 1.491069  Accuracy: 66.41%        Best: 0.00%
tensor([[ 1.0000e+00, -3.9200e-08,  1.6917e-10,  ...,  1.7462e-10,
          5.8208e-11,  1.4552e-10],
        [-3.9200e-08,  1.0000e+00, -1.2733e-10,  ..., -2.9104e-10,
         -2.3283e-10, -2.3283e-10],
        [ 1.6917e-10, -1.2733e-10,  1.0000e+00,  ...,  1.3970e-09,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 1.7462e-10, -2.9104e-10,  1.3970e-09,  ...,  1.0000e+00,
          7.4579e-11,  7.4579e-11],
        [ 5.8208e-11, -6.9849e-10, -1.1642e-10,  ...,  7.0941e-11,
          1.0000e+00, -8.8912e-09],
        [ 2.9104e-11, -2.3283e-10,  1.1642e-10,  ...,  8.0036e-11,
         -1.4901e-08,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [2304/60000 (4%)]        Loss: 1.373097  Accuracy: 70.31%        Best: 0.00%
tensor([[ 1.0000e+00,  4.1523e-08,  3.8199e-11,  ..., -5.8208e-11,
          4.3656e-10,  3.4925e-10],
        [ 4.1523e-08,  1.0000e+00, -5.2751e-11,  ..., -5.8208e-11,
          2.3283e-10,  3.4925e-10],
        [ 3.8199e-11, -5.2751e-11,  1.0000e+00,  ..., -9.3132e-10,
          4.3656e-11,  1.1642e-10],
        ...,
        [-5.8208e-11, -5.8208e-11, -9.3132e-10,  ...,  1.0000e+00,
         -9.0949e-12, -2.8194e-11],
        [ 5.8208e-11, -2.3283e-10,  4.3656e-11,  ..., -4.3656e-11,
          1.0000e+00, -1.6080e-09],
        [ 5.8208e-11,  0.0000e+00,  0.0000e+00,  ..., -5.8208e-11,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [2432/60000 (4%)]        Loss: 1.036170  Accuracy: 70.31%        Best: 0.00%
tensor([[ 1.0000e+00, -7.6093e-08, -9.0949e-12,  ...,  3.4925e-10,
         -5.8208e-11,  8.7311e-11],
        [-7.6093e-08,  1.0000e+00, -4.6384e-10,  ..., -5.8208e-11,
         -4.6566e-10, -2.3283e-10],
        [-9.0949e-12, -4.6384e-10,  1.0000e+00,  ...,  0.0000e+00,
         -2.9104e-11, -1.1642e-10],
        ...,
        [ 3.4925e-10, -5.8208e-11,  0.0000e+00,  ...,  1.0000e+00,
          5.2751e-11,  3.8199e-11],
        [ 0.0000e+00, -4.6566e-10, -8.7311e-11,  ...,  4.9113e-11,
          1.0000e+00, -2.2010e-09],
        [ 5.8208e-11,  1.1642e-10, -2.3283e-10,  ..., -7.2760e-12,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [2560/60000 (4%)]        Loss: 1.293356  Accuracy: 72.66%        Best: 0.00%
tensor([[ 1.0000e+00,  5.3933e-08, -1.2733e-10,  ..., -1.7462e-10,
         -8.7311e-11,  5.8208e-11],
        [ 5.3933e-08,  1.0000e+00, -2.1100e-10,  ..., -1.1642e-10,
          2.3283e-10,  1.1642e-10],
        [-1.2733e-10, -2.1100e-10,  1.0000e+00,  ..., -6.9849e-10,
         -5.8208e-11, -1.1642e-10],
        ...,
        [-1.7462e-10, -1.1642e-10, -6.9849e-10,  ...,  1.0000e+00,
         -1.5916e-10, -7.4579e-11],
        [-2.0373e-10,  0.0000e+00, -2.3283e-10,  ..., -6.2755e-11,
          1.0000e+00, -1.8481e-09],
        [-8.7311e-11,  3.4925e-10,  0.0000e+00,  ..., -1.4552e-11,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [2688/60000 (4%)]        Loss: 0.922459  Accuracy: 82.03%        Best: 0.00%
tensor([[ 1.0000e+00, -4.6152e-08, -1.9463e-10,  ..., -1.1642e-10,
         -1.1642e-10, -1.4552e-11],
        [-4.6152e-08,  1.0000e+00,  1.2915e-10,  ..., -3.4925e-10,
          0.0000e+00, -2.3283e-10],
        [-1.9463e-10,  1.2915e-10,  1.0000e+00,  ...,  6.9849e-10,
         -2.9104e-11, -2.3283e-10],
        ...,
        [-1.1642e-10, -3.4925e-10,  6.9849e-10,  ...,  1.0000e+00,
         -5.8208e-11,  1.8190e-12],
        [ 2.9104e-11,  2.3283e-10,  5.8208e-11,  ..., -1.0186e-10,
          1.0000e+00, -1.4916e-08],
        [-1.3097e-10, -3.4925e-10, -1.1642e-10,  ..., -1.4552e-11,
         -1.4901e-08,  1.0000e+00]], grad_fn=<MmBackward>)
Train Epoch: 0 [2816/60000 (4%)]        Loss: 0.933200  Accuracy: 76.56%        Best: 0.00%
tensor([[ 1.0000e+00,  3.9247e-08, -4.9113e-11,  ...,  5.8208e-11,
         -5.8208e-11, -1.1642e-10],
        [ 3.9247e-08,  1.0000e+00, -5.1568e-10,  ...,  2.3283e-10,
         -2.3283e-10,  0.0000e+00],
        [-4.9113e-11, -5.1568e-10,  1.0000e+00,  ...,  2.3283e-10,
         -5.8208e-11,  0.0000e+00],
        ...,
        [ 5.8208e-11,  2.3283e-10,  2.3283e-10,  ...,  1.0000e+00,
          1.1369e-10, -3.6380e-11],
        [-1.1642e-10, -6.9849e-10,  2.9104e-11,  ...,  4.7294e-11,
          1.0000e+00, -5.7717e-09],
        [-1.6007e-10,  0.0000e+00, -1.1642e-10,  ..., -1.4552e-11,
          0.0000e+00,  1.0000e+00]], grad_fn=<MmBackward>)`

**Comment by Lezcano** [comment]
It cannot be exactly the identity due to numerical errors. If you need more precision, you can always use double precision, as you may already be doing, at the expense of a considerable drop in performance on GPU.

In the future, to check that something is close to the identity, consider doing what I suggested above:
```python
W = model.rnn.recurrent_kernel.weight
print(torch.dist(W.T @ W, torch.eye(W.shape[-1], device=W.device))
```

**Comment by Lezcano** [comment]
Can we mark this issue as resovled?

**Comment by liumiao-p** [comment]
ok, thank you very much!
