### ISSUE TITLE
Does Euclidean optimizer fail when the matrix is not skew-symmetric or skew-Hermitian?

### ISSUE THREAD

**Issue by liumiao-p** [Lezcano/geotorch#27]
If the last two dimensions of tensor are not square, `torus_init_` cannot be applied to the tensor.
Then the tensor cannot be filled with skew-symmetric  matrix, then exponential map fail, then geometry optimization cannot be transformed into Euclidean optimization. Is that the case?

With respect to non-square matrix, how can  geometry optimization be transformed into Euclidean optimization？

**Comment by Lezcano** [comment]
Please have a look at the docs: https://geotorch.readthedocs.io/en/latest/orthogonal/stiefel.html
