### ISSUE TITLE
Initial values seem to be overwritten when parameterization is applied, even if the constraint was already satisfied.

### ISSUE THREAD

**Issue by erpayne1129** [Lezcano/geotorch#28]
I attempted to constrain a tensor using `geotorch.sphere(my_model, "my_param_name", my_radius)`, but found that after registering the parameterization the original values of `my_model.my_param_name` (which were already on the sphere) had been significantly perturbed. Is this behavior expected or is it possible that I made a mistake in my usage of the `sphere` function? It is very important that I start my optimization from the initial values I have pre-selected ([x,y,z] coordinates on a polyhedron), so if it's the norm that registering a constraint agitates the initialization, that will really limit its usefulness in some cases.

**Comment by erpayne1129** [comment]
I have worked around the issue by setting my initial values after registering the constraints. It might be worth mentioning in the documentation somewhere about how/when to set initial values so other people avoid the same confusion.

**Comment by Lezcano** [comment]
Initialising the model after putting the constraints is the right way to go. Note that this is described in the main example in the README:
```python
        # Weights are initialized to a random value when you put the constraints, but
        # you may re-initialize them to a different value by assigning to them
```
but also in some parts of the docs.

**Comment by Lezcano** [comment]
Closing this one for now.
