### ISSUE TITLE
paper about low-rank

### ISSUE THREAD

**Issue by liumiao-p** [Lezcano/geotorch#36]
Hi, I am doing research based on low-rank manifold. I have difficulty in understanding  the idea behind your implementation of  low-rank. So I wonder is there any paper explaining it? I know you have paper for orthogonality, but I'm not sure whether   you have paper for low-rank. If you have, could you please tell me?

**Comment by Lezcano** [comment]
It is not published, but it follows the ideas laid out in my paper:
https://arxiv.org/abs/1909.09501
and from a more mathematical perspective, in my thesis:
https://arxiv.org/abs/2203.04794

From a theoretical perspective, this approach falls in the framework laid out in Chapter 4 in my thesis.

**Comment by Lezcano** [comment]
closing for now, feel free to ask and I'll reopen it if needed.
