### ISSUE TITLE
Constraints API doesn't work when OpenCV is imported

### ISSUE THREAD

**Issue by suchusername** [Lezcano/geotorch#37]
Hi, thanks for convenient library. I may have found an issue or unintended behaviour.

**Description**

Constrains API seems to fail when `cv2` is imported.

**Minimal example**

```py
import torch, geotorch

class Test(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.param = torch.nn.Linear(3, 1)
        geotorch.sphere(self.param)        
        print(self.param.weight)
        
    def forward(self, x):
        pass
    
t = Test()
```
This code prints out `tensor([[ 0.8085, -0.3293, -0.4876]], grad_fn=<MulBackward0>)` as expected.

```py
import torch, geotorch
import cv2

class Test(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.param = torch.nn.Linear(3, 1)
        geotorch.sphere(self.param)        
        print(self.param.weight)
        
    def forward(self, x):
        pass
    
t = Test()
```
This code prints out `tensor([[nan, nan, nan]], grad_fn=<MulBackward0>)`.

**Expected behaviour**

Code works the same way regardless of whether `cv2` is imported or not.

When I remove the line `geotorch.sphere(...)`, the code works as expected, so I assume it's an issue with `geotorch`.

**Environment**

I am using Python 3.8.10. Library versions:
- `cv2` -> `4.5.4`
- `torch` -> `1.11.0+cu102`
- `geotorch` -> `0.3.0` (installed with `pip install git+https://github.com/Lezcano/geotorch/`)

**Comment by Lezcano** [comment]
Wow, this is certainly unexpected. Thank you for the short repro! I'll look into that soon

**Comment by suchusername** [comment]
FYI I have attempted to replicate this issue on another machine, and the code worked fine.

I assume it has something to do with my OpenCV installation (I built it from source, rather than just pip installed it). However, I have no idea why it can affect `torch` and `geotorch`... 

I guess I will close this issue.
