### ISSUE TITLE
Fail to apply constraints when layer is on cuda

### ISSUE THREAD

**Issue by Szy-Young** [lezcano/geotorch#39]
Hi @lezcano, thanks for open-sourcing this wonderful library!

When I try to optimize a SE(3) transformation, I create it as a torch.nn.Linear layer and apply orthogonal constraint on its 3x3 weight. Everything works well on cpu, but when I put the Linear layer on cuda I got this error:
![Screenshot from 2022-11-20 21-06-29](https://user-images.githubusercontent.com/30883678/202903609-34257bab-bdf9-4f3b-a8ce-066640d67d90.png)

Could you help me take a look at this? Thanks!

**Comment by lezcano** [comment]
Could you try in the last PyTorch version? Also, would you mind providing a short script that reproduces the issue?

**Comment by Szy-Young** [comment]
> Could you try in the last PyTorch version? Also, would you mind providing a short script that reproduces the issue?

Hi @lezcano, I tried with the newer PyTorch 1.11 version. The problem still exists.
Here is the short script that reproduces the issue:
```
import torch
import torch.nn as nn
import geotorch

T = nn.Linear(3, 3, bias=True)
geotorch.orthogonal(T, 'weight')           # This line works fine

T = nn.Linear(3, 3, bias=True).cuda()
geotorch.orthogonal(T, 'weight')           # Error reported when executing this line
```

**Comment by lezcano** [comment]
Sorry, but I'm not able to reproduce it.

Using PyTorch master (e.g. the nightly version available in pip), cloning geotorch, and installing the master branch with `pip setup.py develop` that script does not error out.

Could you use this setup see if it solves tahe issue for you?

**Comment by Szy-Young** [comment]
The newest PyTorch version (1.13) solves it! Very thanks for your help:)
