### ISSUE TITLE
I am very interested in this subject.

### ISSUE THREAD

**Issue by HongLouyemeng** [lezcano/geotorch#41]
**Hi lezcano**
          Could you **provide me with some advice** If I want to study the topic of **optimization of manifolds and Euclid** in the long term.
  Now, **The only deficiency is I  have only a basic knowledge of Riemann manifolds, fiber bundle and topology**

**Comment by lezcano** [comment]
To learn about optimisation on manifolds, differential and Riemannian geometry is essential. You can have a look at Lee's book "Introduction to Smooth Manifolds" for a basic introduction, or take / read relevant courses in these areas. Find a course that you feel comfortable reading from a university and read through it. Then take another one and repeat :)

Depending on your maths level, you may be comfortable reading more advanced books on the topic. A second book on Riemannian geometry that I particularly like is Peter Petersen's "Riemannian Geometry", but again, I would not use this one as an introductory book.

**Comment by HongLouyemeng** [comment]
> To learn about optimisation on manifolds, differential and Riemannian geometry is essential. You can have a look at Lee's book "Introduction to Smooth Manifolds" for a basic introduction, or take / read relevant courses in these areas. Find a course that you feel comfortable reading from a university and read through it. Then take another one and repeat :)
> 
> Depending on your maths level, you may be comfortable reading more advanced books on the topic. A second book on Riemannian geometry that I particularly like is Peter Petersen's "Riemannian Geometry", but again, I would not use this one as an introductory book.

Thanks for the reply, I will try it.😊😊
