### ISSUE TITLE
Slow when using high-dimensional orthogonal weight

### ISSUE THREAD

**Issue by jihwanp** [lezcano/geotorch#46]
Hi, I encounter efficiency issue when i use an orthogonal linear layer of more than 2048x2048. It cost about 17Gflops. It seems that most of the computation is done in orthogonalization.
Is it okay to copy the orthogonalized weight to the linear layer weight during inference time so that i can skip the orthogonalization process? 
Thanks

**Comment by lezcano** [comment]
If you want to do inference post training, you might want to use https://pytorch.org/docs/stable/generated/torch.nn.utils.parametrize.remove_parametrizations.html and remove the parametrisation, replacing it with the current value it has.

**Comment by jihwanp** [comment]
Thanks for the quick reply. I'll try it
